### ISSUE TITLE
model.pixelscale vs self.pixelscale

### ISSUE THREAD

**Issue by eragusa** [cpinte/pymcfost#31]
I was running a script I had written a few months ago and encountered the following error in the line.py file (but same applies to image.py)

293     if per_beam:
  294       beam_area = bmin * bmaj * np.pi / (4.0 * np.log(2.0))
--> 295       pix_area = model.pixelscale**2
  296       im *= beam_area/pix_area
  297       unit = unit.replace(“pixel-1”, “beam-1")

NameError: name ‘model’ is not defined

If I look at the history of changes of line.py the pixelscale variable was well defined as self.pixelscale. I am wondering if I am missing something or that “model” should actually be “self” and simply got there due to copy and paste from CASA_simdata.py. Could change it locally, but I thought it might be helpful to report it in case it should not be there.
Thanks

**Comment by cpinte** [comment]
I believe this has been fixed.

**Comment by cpinte** [comment]
Thanks
