### ISSUE TITLE
Error when reading molecule section of parameter file

### ISSUE THREAD

**Issue by briley-lewis** [cpinte/pymcfost#32]
If nmol, level_max, or n_speed are written as values with decimal points in the parameter file (e.g. "1.0" vs. "1") then `model = mcfost.SED("data_th/")` throws an error that line[1] can't be converted to an integer. I worked around this by changing the values in the parameter file directly, but it'd be nice if the function could handle this! :)

**Comment by cpinte** [comment]
Thanks for the suggestion. 
Those parameters are integer, so I believe it makes sense that pymcfost does not accept floats here.
