### ISSUE TITLE
Image object error while reading parameter file

### ISSUE THREAD

**Issue by briley-lewis** [cpinte/pymcfost#33]
When trying to create an Image object using `im = pymcfost.Image('data_2.0')` I get an error related to reading in the parameter file. It seems as though pymcfost is expecting a format of the parameter file that is not generated automatically by mcfost in this folder.
![image](https://user-images.githubusercontent.com/10789514/183487967-8d7b5727-086c-46b1-a58f-2a2c42eb3b40.png)

This is the contents of the parameter file housed in data_2.0, as auto-generated by mcfost:
![image](https://user-images.githubusercontent.com/10789514/183488035-9731a0af-8324-4159-bbf8-a9414ed10360.png)

If I replace the auto-generated .para file with the original parameter file used to run mcfost, everything works fine except for the issue that I opened previously.

**Comment by cpinte** [comment]
Thanks. I believe it works now.
