### ISSUE TITLE
Parameter File Writing, Star z position

### ISSUE THREAD

**Issue by jrhom1** [cpinte/pymcfost#42]
This is a pretty simple fix, but I noticed that when using my python wrapper to modify/rewrite parameter files, the Star z position was actually being written as the star x position! Indeed, in parameters.py, on Line 511:
txt += f"""  {self.stars[k].Teff} {self.stars[k].R} {self.stars[k].M} {self.stars[k].x} {self.stars[k].y} **{self.stars[k].x}** {self.stars[k].is_bb}  Temp, radius (solar radius),M (solar mass),x,y,z (AU), is a blackbody?

Probably not something people worry about much unless you're making asymmetric disks!

**Comment by cpinte** [comment]
Many thanks!
This is fixed with commit [ed137d6](https://github.com/cpinte/pymcfost/commit/ed137d630764e7872e6ba54cdb0db0d1c697eafb)
